# Generated by Django 4.2.6 on 2024-06-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
